version: '3'
services:
  auldfellas:
    build: auldfellas
    network_mode: host
    ports:
      - 2552:2552
    depends_on:
      - broker
  dodgydrivers:
    build: dodgydrivers
    network_mode: host
    ports:
      - 2553:2553
    depends_on:
      - broker
  girlpower:
    build: girlpower
    network_mode: host
    ports:
      - 2554:2554
    depends_on:
      - broker
  broker:
    build: broker
    network_mode: host
    ports:
      - 2551:2551
  client:
    build: client
    network_mode: host
    ports:
      - 2555:2555
    depends_on:
      - auldfellas
      - dodgydrivers
      - girlpower
