version: '3'

services:
  broker:
    build: broker
    ports:
      - "9000:9000"
  auldfellas:
    build: auldfellas
    ports:
      - "9001:9001"
    depends_on:
      - broker
  dodgydrivers:
    build: dodgydrivers
    ports:
      - "9003:9003"
    depends_on:
      - broker
  girlpower:
    build: girlpower
    ports:
      - "9002:9002"
    depends_on:
      - broker
  client:
    restart: on-failure
    build: client
    environment:
      HOSTNAME: broker
    depends_on:
      - broker
      - auldfellas
      - dodgydrivers
      - girlpower